### ISSUE TITLE
Quels sont les différent champs à avoir dans la page participate

### ISSUE THREAD

**Issue by shiftSh** [Art-Sign/Art-Sign#75]
Pour chacun des formulaires

- **Participez à l'association**
- **Devenir Membre**
- **Faire un don**

**Comment by Emeric54** [comment]
En fait, pour les 3 formulaires, les champs seraient les mêmes. Le mieux serait sûrement d'avoir un seul formulaire, avec lors de la validation, la possibilité de choisir entre les trois options.

**Comment by shiftSh** [comment]
ok
